# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials-3
main: net.ess3.bukkit.BukkitPlugin
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${build.number}
website: http://tiny.cc/EssentialsWiki
description: Provides an essential, core set of commands for Bukkit.
authors: ["Essentials Team", "http://contributors.ess3.net"]
commands:
  afk:
    description: Меняет Ваш статус на "Отошел".
    usage: /<command>
    aliases: [eafk]
  antioch:
    description: Небольшой сюрприз для операторов.
    usage: /<command> [message]
    aliases: [eantioch,grenade,tnt,egrenade,etnt]
  back:
    description: Возвращает на позицию до введения команды tp/spawn/warp.
    usage: /<command>
    aliases: [eback,return,ereturn]
  backup:
    description: Запуск создания резервной копии.
    usage: /<command>
    aliases: [ebackup]
  balance:
    description: Показывает баланс игрока.
    usage: /<command> [игрок]
    aliases: [bal,money,emoney,ebalance,ebal]
  balancetop:
    description: Показывает топ балансов игроков.
    usage: /<command> [pagenumber|hide [игрок]|force]
    aliases: [baltop,ebaltop,ebalancetop]
  ban:
    description: Блокирует игрока.
    usage: /<command> <игрок> [причина]
    aliases: [eban]
  banip:
    description: Блокирует IP адресс.
    usage: /<command> <address>
    aliases: [ebanip]
  book:
    description: Позволяет открытие и редактирование запечатанных книг.
    usage: /<command> [title|author [name]]
    aliases: [ebook]
  break:
    description: Разрушает блок размещенный под курсором.
    usage: /<command>
    aliases: [ebreak]
  broadcast:
    description: Передает сообщение для всего сервера.
    usage: /<command> <msg>
    aliases: [ebroadcast,bcast,ebcast,shout,eshout,bc,ebc]
  bigtree:
    description: Создает большое дерево под курсором.
    usage: /<command> <tree|redwood|jungle>
    aliases: [ebigtree]
  burn:
    description: Зажигает игрока.
    usage: /<command> <игрок> <seconds>
    aliases: [eburn]
  clearinventory:
    description: Ичищает инвентарь.
    usage: /<command>
    aliases: [ci,eci,clearinvent,clean,eclean,eclearinvent,eclearinventory]
  compass:
    description: Описывает Ваше текущее месторасположение.
    usage: /<command>
    aliases: [ecompass,direction,edirection]
  delhome:
    description: Удаляет точку дома
    usage: /<command> [player:]<name>
    aliases: [edelhome,remhome,rmhome,eremhome,ermhome]
  deljail:
    description: Удаляет тюрьму
    usage: /<command> <jailname>
    aliases: [edeljail]
  delwarp:
    description: Удаляет указанный варп.
    usage: /<command> <warp>
    aliases: [edelwarp,remwarp,rmwarp,eremwarp,ermwarp]
  depth:
    description: Выводит высоту относительно уровня моря.
    usage: /depth
    aliases: [edepth]
  eco:
    description: Управление экономикой сервера.
    usage: /<command> <give|take|reset> <игрок> <amount>
    aliases: [economy,eeco,eeconomy]
  enchant:
    description: Зачаровывает предмет в руке.
    usage: /<command> <enchantmentname> [level]
    aliases: [enchantment,eenchant,eenchantment]
  enderchest:
    description: Открывает Ваш сундук ендера.
    usage: /<command> [игрок]
    aliases: [endersee,echest,eenderchest,eendersee,eechest]
  essentials:
    description: Перезагружает Essentials.
    usage: /<command>
    aliases: [ess]
  exp:
    description: Пополнить, указать или узнать уровень опыта игрока.
    usage: /<command> [show|set|give] [playername [amount]]
    aliases: [eexp,xp]
  ext:
    description: Тушит игроков.
    usage: /<command> [игрок]
    aliases: [extinguish,eext,eextinguish]
  feed:
    description: Уталяет голод.
    usage: /<command> [игрок]
    aliases: [efeed,eat,eeat]
  fly:
    description: Переключает режим полета!
    usage: /<command> [игрок] [on|off]
    aliases: [efly]
  itemdb:
    description: Ищет элемент.
    usage: /<command> <item>
    aliases: [eitemdb,itemno,eitemno,durability,dura,edura,edurability]
  fireball:
    description: Бросает огненый шар.
    usage: /<command> [small|skull]
    aliases: [efireball,fireskull,efireskull,fireentity,efireentity]
  firework:
    description: Позволяет изменять стак фейерверков.
    usage: /<command> <<meta param>|power [amount]|clear|fire [amount]>
    aliases: [efirework]
  gamemode:
    description: Переключает игровой режик игрока.
    usage: /<command> [игрок]
    aliases: [gm,creative,creativemode,egamemode,ecreative,ecreativemode,egm]
  getpos:
    description: Показывает Ваши координаты или координаты указанного игрока.
    usage: /<command> [игрок]
    aliases: [coords,egetpos,position,eposition,whereami,ewhereami]
  gc:
    description: Показывает статистику по мусоры и ТПС; актуально для разработчиков.
    usage: /<command>
    aliases: [elag,lag,mem,memory,egc,emem,ememory]
  give:
    description: Выдает игроку элемент.
    usage: /<command> <игрок> <item|numeric> [amount <enchantmentname[:level]> ...]
    aliases: [egive]
  god:
    description: Делает Вас богом.
    usage: /<command> [игрок] [on|off]
    aliases: [tgm,godmode,egod,etgm,egodmode]
  hat:
    description: Предоствляет новые шапки для игрока
    usage: /<command> [remove]
    aliases: [ehat]
  heal:
    description: Восстанвливает вашу жизнь или жизнь указанного игрока.
    usage: /<command> [игрок]
    aliases: [eheal]
  help:
    description: Показывает список доступных команд.
    usage: /<command> [search term] [page]
    aliases: [ehelp]
  helpop:
    description: Управление онлайн администрацией.
    usage: /<command> <message>
    aliases: [ehelpop,amsg,eamsg,ac,eac,ehelpop]
  home:
    description: Телепортирует Вас домой.
    usage: /<command> [player:][name]
    aliases: [ehome,homes,ehomes]
  ignore:
    description: Игнорирование других игроков.
    usage: /<command> <player|list>
    aliases: [eignore]
  info:
    description: Показывает информацию указанную владельцем сервера.
    usage: /<command> [chapter] [page]
    aliases: [ifo,einfo,eabout,news,enews,eifo]
  invsee:
    description: Показывает инвентарь другого игрока.
    usage: /<command> <игрок>
    aliases: [einvsee]
  item:
    description: Создает элемент.
    usage: /<command> <item|numeric> [amount <enchantmentname[:level]> ...]
    aliases: [i,eitem]
  jails:
    description: Список тюрем.
    usage: /<command>
    aliases: [ejails]
  jump:
    description: Прыжок на блок под курсором.
    usage: /<command>
    aliases: [j,ej,jumpto,ejumpto,ejump]
  kick:
    description: Выбрасывает игрока сервера.
    usage: /<command> <игрок> [причина]
    aliases: [ekick]
  kickall:
    description: Выбрасывает с сервера всх игроков.
    usage: /<command> [причина]
    aliases: [ekickall]
  kit:
    description: Предоставляет указанный набор или список наборов.
    usage: /<command> [kit] [игрок]
    aliases: [ekit,kits,ekits]
  kill:
    description: Убивает указанного игрока.
    usage: /<command> <игрок>
    aliases: [ekill]
  killall:
    description: Убивает всех мобов в мире.
    usage: /<command> [mobType] [radius]
    aliases: [ekillall,butcher,ebutcher,mobkill,emobkill]
  kittycannon:
    description: Выбрасывает взрывающегося котенка на опонента.
    usage: /<command>
  list:
    description: Показывет список игроков онлайн.
    usage: /<command>
    aliases: [playerlist,who,online,plist,eplist,elist,ewho,eplayerlist,eonline]
  lightning:
    description: Сила Тора. Ударяет в точку под курсором или игрока.
    usage: /<command> [игрок] [power]
    aliases: [strike,smite,thor,shock,elightning,estrike,esmite,ethor,eshock]
  mail:
    description: Управляет внутриигровой почтой.
    usage: /<command> [read|clear|send [to] [message]|sendall [message]]
    aliases: [email]
  me:
    description: Описывает действие в контексте игрока.
    usage: /<command> <description>
    aliases: [action,describe,eme,eaction,edescribe]
  more:
    description: Увеличивает колличество елементов в стаке до максимума.
    usage: /<command> [all]
    aliases: [emore]
  motd:
    description: Показывает сообщение дня.
    usage: /<command>
    aliases: [emotd]
  msg:
    description: Отправляет частное сообщение игроку.
    usage: /<command> <to> <message>
    aliases: [m,t,emsg,tell,etell,whisper,ewhisper]
  mute:
    description: Вбивает или вынимает кляп у игрока.
    usage: /<command> <игрок> [datediff]
    aliases: [emute]
  near:
    description: Показывает игроков находящихся рядом.
    usage: /<command> [playername] [radius]
    aliases: [nearby,enear,enearby]
  nick:
    description: Меняет Ваш ник или ник другого игрока.
    usage: /<command> [игрок] <nickname|off>
    aliases: [enick]
  nuke:
    description: Создает взрывной дождь.
    usage: /<command> [игрок]
    aliases: [enuke]
  pay:
    description: Передает игругому игроку указанную сумму.
    usage: /<command> <игрок> <amount>
    aliases: [epay]
  ping:
    description: Pong!
    usage: /<command>
    aliases: [pong,echo,echo,eping,epong]
  powertool:
    description: Привязывает команду к предмету в руке.
    usage: /<command> [l:|a:|r:|c:|d:][command] [arguments] - {player} can be replaced by name of a clicked player.
    aliases: [pt,epowertool,ept]
  powertooltoggle:
    description: Включает или выключает все супер интструменты.
    usage: /<command>
    aliases: [ptt,epowertooltoggle,pttoggle,epttoggle,eptt]
  ptime:
    description: Указывает время у игрока. Добавьте префикс @ для исправления.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] [player|*]
    aliases: [playertime, eptime, eplayertime]
  r:
    description: Быстрый ответ на последнее частное сообщение.
    usage: /<command> <message>
    aliases: [er,reply,ereply]
  realname:
    description: Показывает имя игрока основываясь на нике.
    usage: /<command> <nickname>
    aliases: [erealname]
  recipe:
    description: Показывает рецепты крафта.
    usage: /<command> <item> [number]
    aliases: [erecipe]
  remove:
    description: Удаляет все сущности в мире.
    usage: /<command> <drops|arrows|boats|minecarts|xp|paintings> [radius]
    aliases: [eremove]
  repair:
    description: Восстанавливает предмет в руке или все предмены.
    usage: /<command> <hand|all>
    aliases: [fix,erepair,efix]
  rules:
    description: Показывает правила сервера.
    usage: /<command>
    aliases: [erules]
  seen:
    description: Показывает время последнего выхода с сервера.
    usage: /<command> <playername>
    aliases: [eseen]
  sell:
    description: Продает предмет в руке.
    usage: /<command> <itemname|id|hand|inventory|blocks> [-][amount]
    aliases: [esell]
  sethome:
    description: Указыват точку дома.
    usage: /<command> [[player:]name]
    aliases: [esethome]
  setjail:
    description: Создает тюрьму с указанным именем [jailname]
    usage: /<command> <jailname>
    aliases: [esetjail]
  setspawn:
    description: Пказывает точку спавна.
    usage: /<command> <group>
    aliases: [esetspawn]
  setwarp:
    description: Создает новый варп.
    usage: /<command> <warp>
    aliases: [createwarp,esetwarp]
  setworth:
    description: Указывает цену продаши элемента.
    usage: /<command> [itemname|id] <price>
    aliases: [esetworth]
  socialspy:
    description: Переключает видимость скрытых команд в чате.
    usage: /<command> [игрок] [on|off]
    aliases: [esocialspy]
  spawn:
    description: Телепортирует на спавн.
    usage: /<command> [игрок]
    aliases: [espawn]
  spawner:
    description: Указывает тип моба в спавнере.
    usage: /<command> <mob>
    aliases: [espawner,changems,echangems]
  spawnmob:
    description: Создает моба.
    usage: /<command> <mob>[:data][,<mount>[:data]] [amount] [игрок]
    aliases: [espawnmob,mob,emob]
  speed:
    description: Изменяет Вашу скорость.
    usage: /<command> <speed> [игрок]
    aliases: [flyspeed,walkspeed,fspeed,wspeed,eflyspeed,ewalkspeed,efspeed,ewspeed,espeed]
  sudo:
    description: Вызывает команду от имени другого игрока.
    usage: /<command> <игрок> <command [args]>
    aliases: [esudo]
  suicide:
    description: Самолинчевание.
    usage: /<command>
    aliases: [esuicide]
  tempban:
    description: Временно блокирует игрока.
    usage: /<command> <playername> <datediff>
    aliases: [etempban]
  thunder:
    description: Включает/выключает гром.
    usage: /<command> <true/false> [duration]
    aliases: [ethunder]
  time:
    description: Показывает/Измняет временя на сервере. По-умолчанию только в текущем мире.
    usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [etime, day, night]
  togglejail:
    description: Садит или отпускает из тюрмы указанного игрока.
    usage: /<command> <игрок> <jailname> [datediff]
    aliases: [tjail,jail,ejail,unjail,eunjail,etogglejail]
  top:
    description: Телепортирует на самую высокую точку.
    usage: /<command>
    aliases: [etop]
  tp:
    description: Телепортирует к игроку.
    usage: /<command> <игрок> [otherplayer]
    aliases: [tele,teleport,eteleport,etele,etp,tp2p,etp2p]
  tpa:
    description: Запрошивает разрешение на телепорт на игрока.
    usage: /<command> <игрок>
    aliases: [call,tpask,etpask,etpa,ecall]
  tpaall:
    description: Разрашиает телефорт всех игроков.
    usage: /<command> <игрок>
    aliases: [etpaall]
  tpaccept:
    description: Принимает запрос на телепортирование.
    usage: /<command> [otherplayer]
    aliases: [tpyes,etpaccept,etpyes]
  tpahere:
    description: Запрашивает телепортирование другого игрока к Вам.
    usage: /<command> <игрок>
    aliases: [come,etpahere,ecome]
  tpall:
    description: Телепортирует всех игроков к другому игроку.
    usage: /<command> <игрок>
    aliases: [etpall]
  tpdeny:
    description: Откроняет запрос на телепортацию.
    usage: /<command>
    aliases: [tpno,etpdeny,etpno]
  tphere:
    description: Телепортирует игрока к Вам.
    usage: /<command> <игрок>
    aliases: [s,etphere]
  tpo:
    description: Телепртирование с игнорированием tptoggle.
    usage: /<command> <игрок> [otherplayer]
    aliases: [etpo]
  tpohere:
    description: Телепртирование к себе с игнорированием tptoggle.
    usage: /<command> <игрок>
    aliases: [etpohere]
  tppos:
    description: Телепортирование на указанные координаты.
    usage: /<command> <x> <y> <z> [yaw] [pitch]
    aliases: [etppos]
  tptoggle:
    description: Блокирует все формы телефортации.
    usage: /<command>
    aliases: [etptoggle]
  tree:
    description: Создает дерево под курсором.
    usage: /<command> <tree|birch|redwood|redmushroom|brownmushroom|jungle|junglebush|swamp>
    aliases: [etree]
  unban:
    description: Разблокирование указанного игрока.
    usage: /<command> <игрок>
    aliases: [pardon,eunban,epardon]
  unbanip:
    description: Разблокирование указанного IP адреса.
    usage: /<command> <address>
    aliases: [eunbanip,pardonip,epardonip]
  unlimited:
    description: Разрешает размещение бесконечного колличества элементов.
    usage: /<command> <list|item|clear> [игрок]
    aliases: [eunlimited,ul,unl,eul,eunl]
  vanish:
    description: Скрывает Вас от других игроков.
    usage: /<command> [on|off]
    aliases: [evanish]
  warp:
    description: Показывает список варпов или тепортирует на указанный варп.
    usage: /<command> <pagenumber|warp> [игрок]
    aliases: [ewarp,warps,ewarps]
  weather:
    description: Указывает погоду.
    usage: /<command> <storm/sun> [duration]
    aliases: [sky,sun,storm,eweather,esky,esun,estorm]
  whois:
    description: Показывает имя пользователя согласно нику.
    usage: /<command> <nickname>
    aliases: [ewhois]
  workbench:
    description: Открывает верстак
    usage: /<command>
    aliases: [eworkbench,wb,ewb,wbench,ewbench,craft,ecraft]
  world:
    description: Переключение между мирами.
    usage: /<command> [world]
    aliases: [eworld]
  worth:
    description: Считает выручку от предметов в руке.
    usage: /<command> [item] [amount]
    aliases: [eworth,price,eprice]
