# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: TeamCity
website: http://tiny.cc/EssentialsCommands
description: Provides an essential, core set of commands for Bukkit.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally]
commands:
  afk:
    description: Меняет Ваш статус на "Отошел".
    usage: /<command>
    aliases: [eafk,away,eaway]
  antioch:
    description: Небольшой сюрприз для операторов.
    usage: /<command> [message]
    aliases: [eantioch,grenade,tnt,egrenade,etnt]
  back:
    description: Возвращает на позицию до введения команды tp/spawn/warp.
    usage: /<command>
    aliases: [eback,return,ereturn]
  backup:
    description: Запуск создания резервной копии.
    usage: /<command>
    aliases: [ebackup]
  balance:
    description: Показывает баланс игрока.
    usage: /<command> [игрок]
    aliases: [bal,ebal,ebalance,money,emoney]
  balancetop:
    description: Показывает топ балансов игроков.
    usage: /<command> [pagenumber|hide [игрок]|force]
    aliases: [ebalancetop,baltop,ebaltop]
  ban:
    description: Блокирует игрока.
    usage: /<command> <игрок> [причина]
    aliases: [eban]
  banip:
    description: Блокирует IP адресс.
    usage: /<command> <address>
    aliases: [ebanip]
  book:
    description: Позволяет открытие и редактирование запечатанных книг.
    usage: /<command> [title|author [name]]
    aliases: [ebook]
  break:
    description: Разрушает блок размещенный под курсором.
    usage: /<command>
    aliases: [ebreak]
  broadcast:
    description: Передает сообщение для всего сервера.
    usage: /<command> <msg>
    aliases: [bc,ebc,bcast,ebcast,ebroadcast,shout,eshout]
  bigtree:
    description: Создает большое дерево под курсором.
    usage: /<command> <tree|redwood|jungle>
    aliases: [ebigtree,largetree,elargetree]
  burn:
    description: Зажигает игрока.
    usage: /<command> <игрок> <seconds>
    aliases: [eburn]
  clearinventory:
    description: Ичищает инвентарь.
    usage: /<command>
    aliases: [ci,eci,clean,eclean,clear,eclear,clearinvent,eclearinvent,eclearinventory]
  compass:
    description: Описывает Ваше текущее месторасположение.
    usage: /<command>
    aliases: [ecompass,direction,edirection]
  customtext:
    description: Создает команду.
    usage: /<alias> - Указанный в bukkit.yml
  delhome:
    description: Удаляет точку дома
    usage: /<command> [player:]<name>
    aliases: [edelhome,remhome,eremhome,rmhome,ermhome]
  deljail:
    description: Удаляет тюрьму
    usage: /<command> <jailname>
    aliases: [edeljail,remjail,eremjail,rmjail,ermjail]
  delwarp:
    description: Удаляет указанный варп.
    usage: /<command> <warp>
    aliases: [edelwarp,remwarp,eremwarp,rmwarp,ermwarp]
  depth:
    description: Выводит высоту относительно уровня моря.
    usage: /depth
    aliases: [edepth,height,eheight]
  eco:
    description: Управление экономикой сервера.
    usage: /<command> <give|take|reset> <игрок> <amount>
    aliases: [eeco,economy,eeconomy]
  enchant:
    description: Зачаровывает предмет в руке.
    usage: /<command> <enchantmentname> [level]
    aliases: [eenchant,enchantment,eenchantment]
  enderchest:
    description: Открывает Ваш сундук ендера.
    usage: /<command> [игрок]
    aliases: [echest,eechest,eenderchest,endersee,eendersee,ec,eec]
  essentials:
    description: Перезагружает Essentials.
    usage: /<command>
    aliases: [ess]
  exp:
    description: Пополнить, указать или узнать уровень опыта игрока.
    usage: /<command> [show|set|give] [playername [amount]]
    aliases: [eexp,xp]
  ext:
    description: Тушит игроков.
    usage: /<command> [игрок]
    aliases: [eext,extinguish,eextinguish]
  feed:
    description: Уталяет голод.
    usage: /<command> [игрок]
    aliases: [eat,eeat,efeed]
  fly:
    description: Переключает режим полета!
    usage: /<command> [игрок] [on|off]
    aliases: [efly]
  fireball:
    description: Бросает огненый шар.
    usage: /<command> [small|skull]
    aliases: [efireball,fireentity,efireentity,fireskull,efireskull]
  firework:
    description: Позволяет изменять стак фейерверков.
    usage: /<command> <<meta param>|power [amount]|clear|fire [amount]>
    aliases: [efirework]
  gamemode:
    description: Переключает игровой режик игрока.
    usage: /<command> [игрок]
    aliases: [adventure,eadventure,adventuremode,eadventuremode,creative,eecreative,creativemode,ecreativemode,egamemode,gm,egm,gma,egma,gmc,egmc,gms,egms,gmt,egmt,survival,esurvival,survivalmode,esurvivalmode]
  gc:
    description: Показывает память, время работы и ТПС.
    usage: /<command> [all]
    aliases: [lag,elag,egc,mem,emem,memory,ememory,uptime,euptime,tps,etps,entities,eentities]
  getpos:
    description: Показывает Ваши координаты или координаты указанного игрока.
    usage: /<command> [игрок]
    aliases: [coords,egetpos,position,eposition,whereami,ewhereami,getlocation,egetlocation,getloc,egetloc]
  give:
    description: Выдает игроку элемент.
    usage: /<command> <игрок> <item|numeric> [amount [itemmeta...]]
    aliases: [egive]
  god:
    description: Делает Вас богом.
    usage: /<command> [игрок] [on|off]
    aliases: [egod,godmode,egodmode,tgm,etgm]
  hat:
    description: Предоствляет новые шапки для игрока
    usage: /<command> [remove]
    aliases: [ehat,head,ehead]
  heal:
    description: Восстанвливает вашу жизнь или жизнь указанного игрока.
    usage: /<command> [игрок]
    aliases: [eheal]
  help:
    description: Показывает список доступных команд.
    usage: /<command> [search term] [page]
    aliases: [ehelp]
  helpop:
    description: Управление онлайн администрацией.
    usage: /<command> <message>
    aliases: [ac,eac,amsg,eamsg,ehelpop]
  home:
    description: Телепортирует Вас домой.
    usage: /<command> [player:][name]
    aliases: [ehome,homes,ehomes]
  ignore:
    description: Игнорирование других игроков.
    usage: /<command> <player|list>
    aliases: [eignore,unignore,eunignore,delignore,edelignore,remignore,eremignore,rmignore,ermignore]
  info:
    description: Показывает информацию указанную владельцем сервера.
    usage: /<command> [chapter] [page]
    aliases: [ifo,einfo,eabout,news,enews,eifo]
  invsee:
    description: Показывает инвентарь другого игрока.
    usage: /<command> <игрок>
    aliases: [einvsee]
  item:
    description: Создает элемент.
    usage: /<command> <item|numeric> [amount <enchantmentname[:level]> ...]
    aliases: [i,eitem,ei]
  itemdb:
    description: Ищет элемент.
    usage: /<command> <item>
    aliases: [dura,edura,durability,edurability,eitemdb,itemno,eitemno]
  jails:
    description: Список тюрем.
    usage: /<command>
    aliases: [ejails]
  jump:
    description: Прыжок на блок под курсором.
    usage: /<command>
    aliases: [j,ej,ejump,jumpto,ejumpto]
  kick:
    description: Выбрасывает игрока сервера.
    usage: /<command> <игрок> [причина]
    aliases: [ekick]
  kickall:
    description: Выбрасывает с сервера всх игроков.
    usage: /<command> [причина]
    aliases: [ekickall]
  kill:
    description: Убивает указанного игрока.
    usage: /<command> <player>
    aliases: [ekill]
  kit:
    description: Предоставляет указанный набор или список наборов.
    usage: /<command> [kit] [игрок]
    aliases: [ekit,kits,ekits]
  kittycannon:
    description: Выбрасывает взрывающегося котенка на опонента.
    usage: /<command>
    aliases: [ekittycannon]
  lightning:
    description: Сила Тора. Ударяет в точку под курсором или игрока.
    usage: /<command> [игрок] [power]
    aliases: [elightning,shock,eshock,smite,esmite,strike,estrike,thor,ethor]
  list:
    description: Показывет список игроков онлайн.
    usage: /<command>
    aliases: [elist,online,eonline,playerlist,eplayerlist,plist,eplist,who,ewho]
  mail:
    description: Управляет внутриигровой почтой.
    usage: /<command> [read|clear|send [to] [message]|sendall [message]]
    aliases: [email,eemail]
  me:
    description: Описывает действие в контексте игрока.
    usage: /<command> <description>
    aliases: [action,eaction,describe,edescribe,eme]
  more:
    description: Увеличивает колличество елементов в стаке до максимума.
    usage: /<command> [all]
    aliases: [emore]
  motd:
    description: Показывает сообщение дня.
    usage: /<command>
    aliases: [emotd]
  msg:
    description: Отправляет частное сообщение игроку.
    usage: /<command> <to> <message>
    aliases: [w,m,t,emsg,tell,etell,whisper,ewhisper]
  mute:
    description: Вбивает или вынимает кляп у игрока.
    usage: /<command> <игрок> [datediff]
    aliases: [emute,silence,esilence]
  near:
    description: Показывает игроков находящихся рядом.
    usage: /<command> [playername] [radius]
    aliases: [enear,nearby,enearby]
  nick:
    description: Меняет Ваш ник или ник другого игрока.
    usage: /<command> [игрок] <nickname|off>
    aliases: [enick,nickname,enickname]
  nuke:
    description: Создает взрывной дождь.
    usage: /<command> [игрок]
    aliases: [enuke]
  pay:
    description: Передает игругому игроку указанную сумму.
    usage: /<command> <игрок> <amount>
    aliases: [epay]
  ping:
    description: Pong!
    usage: /<command>
    aliases: [echo,eecho,eping,pong,epong]
  potion:
    description: Добавляет эффект к зелью.
    usage: /<command> <clear|apply|effect:<effect> power:<power> duration:<duration>>
    aliases: [epotion,elixer,eelixer]
  powertool:
    description: Привязывает команду к предмету в руке.
    usage: /<command> [l:|a:|r:|c:|d:][command] [arguments] - {player} can be replaced by name of a clicked player.
    aliases: [epowertool,pt,ept]
  powertooltoggle:
    description: Включает или выключает все супер интструменты.
    usage: /<command>
    aliases: [epowertooltoggle,ptt,eptt,pttoggle,epttoggle]
  ptime:
    description: Указывает время у игрока. Добавьте префикс @ для исправления.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] [player|*]
    aliases: [playertime,eplayertime,eptime]
  pweather:
    description: Указывает погоду у игрока
    usage: /<command> [list|reset|storm|sun|clear] [player|*]
    aliases: [playerweather,eplayerweather,epweather]
  r:
    description: Быстрый ответ на последнее частное сообщение.
    usage: /<command> <message>
    aliases: [er,reply,ereply]
  realname:
    description: Показывает имя игрока основываясь на нике.
    usage: /<command> <nickname>
    aliases: [erealname]
  recipe:
    description: Показывает рецепты крафта.
    usage: /<command> <item> [number]
    aliases: [erecipe]
  remove:
    description: Удаляет все сущности в мире.
    usage: /<command> <all|tamed|drops|arrows|boats|minecarts|xp|paintings|itemframes|endercrystals|monsters|animals|ambient|mobs|[mobType]> [radius] [world]
    aliases: [eremove,butcher,ebutcher,killall,ekillall,mobkill,emobkill]
  repair:
    description: Восстанавливает предмет в руке или все предмены.
    usage: /<command> [hand|all]
    aliases: [fix,efix,erepair]
  rules:
    description: Показывает правила сервера.
    usage: /<command> [chapter] [page]
    aliases: [erules]
  seen:
    description: Показывает время последнего выхода с сервера.
    usage: /<command> <playername>
    aliases: [eseen]
  sell:
    description: Продает предмет в руке.
    usage: /<command> <itemname|id|hand|inventory|blocks> [-][amount]
    aliases: [esell]
  sethome:
    description: Указыват точку дома.
    usage: /<command> [[player:]name]
    aliases: [esethome,createhome,ecreatehome]
  setjail:
    description: Создает тюрьму с указанным именем [jailname]
    usage: /<command> <jailname>
    aliases: [esetjail,createjail,ecreatejail]
  setwarp:
    description: Создает новый варп.
    usage: /<command> <warp>
    aliases: [createwarp,ecreatewarp,esetwarp]
  setworth:
    description: Указывает цену продаши элемента.
    usage: /<command> [itemname|id] <price>
    aliases: [esetworth]
  socialspy:
    description: Переключает видимость скрытых команд в чате.
    usage: /<command> [игрок] [on|off]
    aliases: [esocialspy]
  spawner:
    description: Указывает тип моба в спавнере.
    usage: /<command> <mob> [delay]
    aliases: [changems,echangems,espawner,mobspawner,emobspawner]
  spawnmob:
    description: Создает моба.
    usage: /<command> <mob>[:data][,<mount>[:data]] [amount] [игрок]
    aliases: [mob,emob,spawnentity,espawnentity,espawnmob]
  speed:
    description: Изменяет Вашу скорость.
    usage: /<command> <speed> [игрок]
    aliases: [flyspeed,eflyspeed,fspeed,efspeed,espeed,walkspeed,ewalkspeed,wspeed,ewspeed]
  sudo:
    description: Вызывает команду от имени другого игрока.
    usage: /<command> <игрок> <command [args]>
    aliases: [esudo]
  suicide:
    description: Самолинчевание.
    usage: /<command>
    aliases: [esuicide]
  tempban:
    description: Временно блокирует игрока.
    usage: /<command> <playername> <datediff>
    aliases: [etempban]
  thunder:
    description: Включает/выключает гром.
    usage: /<command> <true/false> [duration]
    aliases: [ethunder]
  time:
    description: Показывает/Измняет временя на сервере. По-умолчанию только в текущем мире.
    usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [day,eday,night,enight,etime]
  togglejail:
    description: Садит или отпускает из тюрмы указанного игрока.
    usage: /<command> <игрок> <jailname> [datediff]
    aliases: [jail,ejail,tjail,etjail,etogglejail,unjail,eunjail]
  top:
    description: Телепортирует на самую высокую точку.
    usage: /<command>
    aliases: [etop]
  tp:
    description: Телепортирует к игроку.
    usage: /<command> <игрок> [otherplayer]
    aliases: [tele,etele,teleport,eteleport,etp,tp2p,etp2p]
  tpa:
    description: Запрошивает разрешение на телепорт на игрока.
    usage: /<command> <игрок>
    aliases: [call,ecall,etpa,tpask,etpask]
  tpaall:
    description: Разрашиает телефорт всех игроков.
    usage: /<command> <игрок>
    aliases: [etpaall]
  tpaccept:
    description: Принимает запрос на телепортирование.
    usage: /<command> [otherplayer]
    aliases: [etpaccept,tpyes,etpyes]
  tpahere:
    description: Запрашивает телепортирование другого игрока к Вам.
    usage: /<command> <игрок>
    aliases: [etpahere]
  tpall:
    description: Телепортирует всех игроков к другому игроку.
    usage: /<command> <игрок>
    aliases: [etpall]
  tpdeny:
    description: Откроняет запрос на телепортацию.
    usage: /<command>
    aliases: [etpdeny,tpno,etpno]
  tphere:
    description: Телепортирует игрока к Вам.
    usage: /<command> <игрок>
    aliases: [s,etphere]
  tpo:
    description: Телепртирование с игнорированием tptoggle.
    usage: /<command> <игрок> [otherplayer]
    aliases: [etpo]
  tpohere:
    description: Телепртирование к себе с игнорированием tptoggle.
    usage: /<command> <игрок>
    aliases: [etpohere]
  tppos:
    description: Телепортирование на указанные координаты.
    usage: /<command> <x> <y> <z> [yaw] [pitch]
    aliases: [etppos]
  tptoggle:
    description: Блокирует все формы телефортации.
    usage: /<command>
    aliases: [etptoggle]
  tree:
    description: Создает дерево под курсором.
    usage: /<command> <tree|birch|redwood|redmushroom|brownmushroom|jungle|junglebush|swamp>
    aliases: [etree]
  unban:
    description: Разблокирование указанного игрока.
    usage: /<command> <игрок>
    aliases: [pardon,eunban,epardon]
  unbanip:
    description: Разблокирование указанного IP адреса.
    usage: /<command> <address>
    aliases: [eunbanip,pardonip,epardonip]
  unlimited:
    description: Разрешает размещение бесконечного колличества элементов.
    usage: /<command> <list|item|clear> [игрок]
    aliases: [eunlimited,ul,unl,eul,eunl]
  vanish:
    description: Скрывает Вас от других игроков.
    usage: /<command> [on|off]
    aliases: [v,ev,evanish]
  warp:
    description: Показывает список варпов или тепортирует на указанный варп.
    usage: /<command> <pagenumber|warp> [игрок]
    aliases: [ewarp,warps,ewarps]
  weather:
    description: Указывает погоду.
    usage: /<command> <storm/sun> [duration]
    aliases: [rain,erain,sky,esky,storm,estorm,sun,esun,eweather]
  whois:
    description: Показывает имя пользователя согласно нику.
    usage: /<command> <nickname>
    aliases: [ewhois]
  workbench:
    description: Открывает верстак
    usage: /<command>
    aliases: [craft,ecraft,wb,ewb,wbench,ewbench,eworkbench]
  world:
    description: Переключение между мирами.
    usage: /<command> [world]
    aliases: [eworld]
  worth:
    description: Считает выручку от предметов в руке.
    usage: /<command> [item] [amount]
    aliases: [eprice,price,eworth]

permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
